// Copyright Rane (elijahrane@gmail.com) 2025
// All rights reserved. Relicensed under AGPL with permission

using System.Linq;
using System.Numerics;
using System.Text.RegularExpressions;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Mono.FireControl;
using Content.Shared._Mono.ShipGuns;
using Content.Shared.Timing;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
using Robust.Shared.Timing;

namespace Content.Client._Mono.FireControl.UI;

[GenerateTypedNameReferences]
public sealed partial class FireControlWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly ILogManager _logger = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    private ISawmill _sawmill = default!;
    public FireControlNavControl Radar => NavRadar;
    public Action? OnServerRefresh;
    public Action? OnWeaponSelectionChanged;
    public List<NetEntity> SelectedWeapons = [];
    private FireControlConsoleBoundInterfaceState? _currentState;
    private Dictionary<string, FireGroupContainer> _groupContainers = [];
    private Dictionary<NetEntity, WeaponBox> _weaponBoxes = [];
    private Dictionary<NetEntity, StartEndTime> _cooldowns = [];
    public FireControlWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        RefreshButton.OnPressed += _ => OnServerRefresh?.Invoke();
        SelectAllButton.OnPressed += SelectAllFireGroups;
        UnselectAllButton.OnPressed += UnselectAllFireGroups;
        _sawmill = _logger.GetSawmill("firecont");
    }

    private void SelectAllFireGroups(BaseButton.ButtonEventArgs args)
    {
        foreach (var (group, container) in _groupContainers)
        {
            container.GroupButton.Pressed = true;
            ToggleFireGroup(group, container.GroupButton);
        }
        UpdateSelectedWeapons();
    }

    private void UnselectAllFireGroups(BaseButton.ButtonEventArgs args)
    {
        foreach (var (group, container) in _groupContainers)
        {
            container.GroupButton.Pressed = false;
            ToggleFireGroup(group, container.GroupButton);
        }
        UpdateSelectedWeapons();
    }

    private void ToggleFireGroup(string group, Button button)
    {
        if (_currentState == null)
            return;
        foreach (var controllable in _currentState.FireGroups[group])
        {
            _weaponBoxes[controllable.NetEntity].GunButton.Pressed = button.Pressed;
        }
    }

    private void UpdateSelectedWeapons()
    {
        SelectedWeapons = [];
        foreach (var (controllable, gunBox) in _weaponBoxes)
        {
            if (gunBox.GunButton.Pressed)
            {
                SelectedWeapons.Add(controllable);
            }
        }
        OnWeaponSelectionChanged?.Invoke();
    }

    public void UpdateWeaponStatus(FireControlConsoleWeaponUpdateMessage message)
    {
        var controllable = message.NetEntity;
        var bar = _weaponBoxes[controllable].AmmoBar;
        bar.MaxValue = message.Capacity;
        bar.Value = message.Shots;
        bar._label.Text = message.Shots.ToString();
        if (message.Cooldown != null)
        {
            _cooldowns[controllable] = message.Cooldown.Value;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        var curTime = _timing.CurTime;
        foreach (var (controllable, duration) in _cooldowns)
        {
            var bar = _weaponBoxes[controllable].CooldownBar;
            var progress = duration.ProgressAt(curTime);
            bar._bar.Value = float.IsFinite(progress) ? progress : 1;
            if (progress >= 1)
            {
                _cooldowns.Remove(controllable);
            }
        }
    }

    public void UpdateStatus(FireControlConsoleBoundInterfaceState state)
    {
        _currentState = state;
        NavRadar.UpdateState(state.NavState);

        if (state.Connected)
        {
            ServerStatus.Text = Loc.GetString("gunnery-window-connected");
            ServerStatus.FontColorOverride = Color.Green;
        }
        else
        {
            RefreshButton.Disabled = false;
            ServerStatus.Text = Loc.GetString("gunnery-window-disconnected");
            ServerStatus.FontColorOverride = Color.Red;
        }

        RefreshWeaponsList(state);
        // UpdateAllFireGroups();
    }

    private void RefreshWeaponsList(FireControlConsoleBoundInterfaceState state)
    {
        var toRemove = new HashSet<NetEntity>(_weaponBoxes.Keys);
        foreach (var controllable in state.FireControllables)
        {
            var group = controllable.Name;
            // Do we need to make a group for this controllable?
            if (!_groupContainers.ContainsKey(group))
            {
                // Group selector button
                var button = new Button
                {
                    ToggleMode = true,
                    Text = group,
                    StyleClasses = { "ButtonSquare OpenRight" },
                    HorizontalExpand = true,
                    Margin = new Thickness(4, 1),
                };
                button.OnToggled += _ =>
                {
                    ToggleFireGroup(group, button);
                    UpdateSelectedWeapons();
                };

                // Container to store fire group's weapon list
                var gunBoxContainer = new BoxContainer()
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    StyleClasses = { "transparentItemList" },
                };

                // Container for the fire group selector and its weapon list
                var groupContainer = new FireGroupContainer()
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    StyleClasses = { "transparentItemList" },
                    GroupButton = button,
                    WeaponBoxes = gunBoxContainer,
                    Children = {button, gunBoxContainer},
                };
                FireGroupsBox.AddChild(groupContainer);
                _groupContainers[group] = groupContainer;
            }
            // Is there already a GunBox for this controllable? If not, make one.
            if (!_weaponBoxes.ContainsKey(controllable.NetEntity))
            {
                var gunBox = new WeaponBox(){Name=group};
                gunBox.AmmoBar.MaxValue = controllable.Capacity ?? 0; // TODO: how to encode if a gun needs an ammo bar?
                gunBox.AmmoBar.Value = controllable.Shots ?? 0;
                // Cooldowns are updated in FrameUpdate
                gunBox.CooldownBar._bar.Value = 1; // TODO: these should be floats
                gunBox.CooldownBar._bar.MaxValue = 1; // TODO: remove the label from CD bar
                gunBox.CooldownBar._label.Text = "";

                gunBox.GunButton.OnToggled += _ =>
                {
                    UpdateSelectedWeapons();
                };
                _weaponBoxes[controllable.NetEntity] = gunBox;
                _groupContainers[group].WeaponBoxes.AddChild(_weaponBoxes[controllable.NetEntity]);
            }
            else
            {
                toRemove.Remove(controllable.NetEntity);
            }
        }

        // Remove stale weapon entries and groups
        foreach (var netEntity in toRemove)
        {
            var weaponBox = _weaponBoxes[netEntity];
            var group = weaponBox.Name;
            _groupContainers[group].WeaponBoxes.RemoveChild(weaponBox);
            if (weaponBox.Parent != null)
            {
                FireGroupsBox.RemoveChild(_groupContainers[group]);
            }
            _weaponBoxes.Remove(netEntity);
        }

        SelectAllButton.Disabled = state.FireControllables.Length == 0;
        UnselectAllButton.Disabled = state.FireControllables.Length == 0;
    }
}

public sealed class FireGroupContainer : BoxContainer
{
    public required Button GroupButton { get; set; }

    public required BoxContainer WeaponBoxes { get; set; }
}

public sealed class WeaponBox : BoxContainer
{
    public Button GunButton;
    public AmmoBar AmmoBar;
    public AmmoBar CooldownBar; // TODO: implement
    public required string Name;

    public WeaponBox()
    {
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        AddChild(GunButton = new Button()
        {
            ToggleMode = true,
            StyleClasses = { "ButtonSquare" },
            HorizontalExpand = true,
            // Margin = new Thickness(4, 1),
            Children =
            {
                new BoxContainer()
                {
                    HorizontalExpand = true,
                    Orientation = LayoutOrientation.Horizontal,
                    // Margin = new Thickness(2, 1);
                    Children =
                    {
                        (AmmoBar = new AmmoBar()),
                        (CooldownBar = new AmmoBar()),
                    },
                },
            },
        });
    }
}
public sealed class AmmoBar : Control
{
    private int _value;
    public int Value
    {
        get
        {
            return _value;
        }
        set
        {
            _value = value;
            _bar.Value = value;
            _label.Text = value.ToString();
        }
    }

    public int MaxValue
    {
        get => field;
        set
        {
            field = value;
            _bar.MaxValue = value;
        }
    }

    public Label _label;
    public ProgressBar _bar;

    public AmmoBar()
    {
        MinHeight = 15;
        HorizontalExpand = true;
        VerticalAlignment = VAlignment.Center;
        AddChild(new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(2, 1),
            Children =
            {
                new Control { MinSize = new Vector2(5, 0) },
                new Control
                {
                    HorizontalExpand = true,
                    MaxHeight = 18,
                    Children =
                    {
                        (_bar = new ProgressBar
                        {
                            MinValue = 0,
                        }),
                        (_label = new Label
                        {
                            StyleClasses = { StyleNano.StyleClassItemStatus },
                            Align = Label.AlignMode.Center
                        })
                    }
                },
                new Control { MinSize = new Vector2(5, 0) },
            }
        });
    }
}
