// Copyright Rane (elijahrane@gmail.com) 2025
// All rights reserved. Relicensed under AGPL with permission

using System.Linq;
using System.Numerics;
using System.Text.RegularExpressions;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Mono.FireControl;
using Content.Shared._Mono.ShipGuns;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
namespace Content.Client._Mono.FireControl.UI;

[GenerateTypedNameReferences]
public sealed partial class FireControlWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly ILogManager _logger = default!;
    private ISawmill _sawmill = default!;
    public FireControlNavControl Radar => NavRadar;
    public Action? OnServerRefresh;
    public Action? OnWeaponSelectionChanged;
    public List<NetEntity> SelectedWeapons = [];
    private FireControlConsoleBoundInterfaceState? _currentState;
    private Dictionary<string, FireGroupContainer> _groupToContainer = [];
    private Dictionary<NetEntity, GunBox> _gunToGunBox = [];

    public FireControlWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        RefreshButton.OnPressed += _ => OnServerRefresh?.Invoke();
        SelectAllButton.OnPressed += SelectAllFireGroups;
        UnselectAllButton.OnPressed += UnselectAllFireGroups;
        _sawmill = _logger.GetSawmill("firecont");
    }

    private void SelectAllFireGroups(BaseButton.ButtonEventArgs args)
    {
        // TODO: this approach still sucks
        foreach (var container in _groupToContainer.Values)
        {
            container.GroupButton.Pressed = true;
        }
        UpdateSelectedWeapons();
    }

    private void UnselectAllFireGroups(BaseButton.ButtonEventArgs args)
    {
        foreach (var container in _groupToContainer.Values)
        {
            container.GroupButton.Pressed = false;
        }
        UpdateSelectedWeapons();
    }

    private void FireGroupButtonOnToggled(BaseButton.ButtonEventArgs args)
    {
        if (_currentState == null)
            return;
        var button = (Button)args.Button;
        var group = button.Text ?? ""; // TODO: no.
        foreach (var controllable in _currentState.FireGroups[group])
        {
            _gunToGunBox[controllable.NetEntity].GunButton.Pressed = button.Pressed;
        }
        UpdateSelectedWeapons();
    }

    private void UpdateSelectedWeapons()
    {
        SelectedWeapons = [];
        foreach (var (controllable, gunBox) in _gunToGunBox)
        {
            if (gunBox.GunButton.Pressed)
            {
                SelectedWeapons.Add(controllable);
            }
        }
        OnWeaponSelectionChanged?.Invoke();
    }


    /// <summary>
    /// Updates the text of a weapon button based on its selection state and manual reload status.
    /// </summary>
    // private void UpdateFireGroup(FireGroupContainer container, List<FireControllableEntry> controllables)
    // {
    //     var button = container.GroupButton;
    //     var ammoBar = container.WeaponAmmoBar;
    //     if (!controllable.AmmoCount.HasValue || !controllable.Capacity.HasValue)
    //     {
    //         ammoBar.MaxValue = 0;
    //         ammoBar.Value = 0;
    //     }
    //     else
    //     {
    //         ammoBar.Value = controllable.AmmoCount.Value;
    //         ammoBar.MaxValue = controllable.Capacity.Value;
    //     }
    //
    //     if (button.Pressed && controllable.HasManualReload && controllable.AmmoCount.HasValue)
    //     {
    //         button.Text = Loc.GetString("gunnery-gun-select-ammo", ("name", controllable.Name), ("ammo", controllable.AmmoCount.Value));
    //
    //         if (controllable.AmmoCount.Value == 0)
    //         {
    //             button.ModulateSelfOverride = Color.Red;
    //         }
    //         else
    //         {
    //             button.ModulateSelfOverride = null;
    //         }
    //     }
    //     else
    //     {
    //         button.Text = Loc.GetString("gunnery-gun-select", ("name", controllable.Name));
    //         button.ModulateSelfOverride = null;
    //     }
    // }
    // private void UpdateFireGroup(string group, FireGroupContainer container)
    // {
    //     if (_currentState == null)
    //         return;
    //     container.AmmoBarContainer.DisposeAllChildren();
    //     foreach (var controllable in _currentState.FireGroups[group])
    //     {
    //         // TODO: this is obviously not going to update properly. get these values from the BUI somehow (timer?).
    //         var bar = new AmmoBar()
    //             { MaxValue = controllable.Capacity ?? 0, Value = controllable.Shots ?? 0  };
    //         if (!controllable.CanFire)
    //         {
    //             bar._bar.ModulateSelfOverride = Color.Red;
    //         }
    //         container.AmmoBarContainer.AddChild(bar);
    //     }
    // }

    /// <summary>
    ///
    /// </summary>
    private void UpdateAllFireGroups()
    {
        // TODO: Find out when this comes up
        if (_currentState == null)
            return;
        List<string>? toRemove = null;
        foreach (var (group, container) in _groupToContainer)
        {
            // TODO: what?
            // var controllable = _currentState?.FireControllables?.FirstOrDefault(c => c.NetEntity == netEntity);
            if (!_currentState.FireGroups.ContainsKey(group))
            {
                if (toRemove == null)
                    toRemove = [];
                toRemove.Add(group);
            }
            else
            {
                // UpdateFireGroup(group, container);
            }
        }

        if (toRemove != null)
        {
            foreach (var group in toRemove)
            {
                _groupToContainer.Remove(group);
            }
        }
    }

    public void UpdateAmmoStatus(NetEntity controllable, int shots, int capacity)
    {
        var bar = _gunToGunBox[controllable].AmmoBar;
        bar.MaxValue = capacity;
        bar.Value = shots;
        bar._label.Text = shots.ToString();
    }

    public void UpdateStatus(FireControlConsoleBoundInterfaceState state)
    {
        _currentState = state;
        NavRadar.UpdateState(state.NavState);

        if (state.Connected)
        {
            ServerStatus.Text = Loc.GetString("gunnery-window-connected");
            ServerStatus.FontColorOverride = Color.Green;
        }
        else
        {
            RefreshButton.Disabled = false;
            ServerStatus.Text = Loc.GetString("gunnery-window-disconnected");
            ServerStatus.FontColorOverride = Color.Red;
        }

        RefreshWeaponsList(state);
        // UpdateAllFireGroups();
    }

    private void RefreshWeaponsList(FireControlConsoleBoundInterfaceState state)
    {
        // Remove fire groups that no longer exist
        // foreach (var staleGroup in GroupToContainer.Keys.Except(state.FireGroups.Keys))
        // {
        //     FireGroupsBox.RemoveChild(GroupToContainer[staleGroup]);
        //     GroupToContainer.Remove(staleGroup);
        // }
        FireGroupsBox.DisposeAllChildren();
        _groupToContainer = [];
        _gunToGunBox = [];
        foreach (var (group, controllables) in state.FireGroups)
        {
            // We already have a container for the fire group, update it
            // if (GroupToContainer.ContainsKey(group))
            // {
            //     UpdateFireGroup(group, GroupToContainer[group]);
            //     continue;
            // }

            // Group selector button
            var button = new Button
            {
                ToggleMode = true,
                Text = group,
                StyleClasses = { "ButtonSquare OpenRight" },
                HorizontalExpand = true,
                Margin = new Thickness(4, 1),
            };
            button.OnToggled += FireGroupButtonOnToggled;

            // Ammo bars
            var gunContainer = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                StyleClasses = { "transparentItemList" },
            };

            // Container for the button and its ammo bars
            var groupContainer = new FireGroupContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                StyleClasses = { "transparentItemList" },
                GroupButton = button,
                GunBoxContainer = gunContainer,
            };
            groupContainer.AddChild(button);
            groupContainer.AddChild(gunContainer);

            foreach (var controllable in controllables)
            {
                var gunBox = new GunBox();
                gunBox.AmmoBar.MaxValue = controllable.Capacity ?? 0; // TODO: how to encode if a gun needs an ammo bar?
                gunBox.AmmoBar.Value = controllable.Shots ?? 0;
                gunBox.CooldownBar.MaxValue = 0; // TODO: remove the label from CD bar
                gunBox.CooldownBar.Value = 0;
                gunContainer.AddChild(gunBox);
                _gunToGunBox[controllable.NetEntity] = gunBox;
            }
            _groupToContainer[group] = groupContainer;
            FireGroupsBox.AddChild(groupContainer);
            // UpdateFireGroup(group, groupContainer);
        }

        SelectAllButton.Disabled = state.FireControllables.Length == 0;
        UnselectAllButton.Disabled = state.FireControllables.Length == 0;
    }
}

public sealed class FireGroupContainer : BoxContainer
{
    public required Button GroupButton { get; set; }

    public required BoxContainer GunBoxContainer { get; set; }
}

public sealed class GunBox : BoxContainer
{
    public Button GunButton;
    public AmmoBar AmmoBar;
    public AmmoBar CooldownBar;

    public GunBox()
    {
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        AddChild(GunButton = new Button()
        {
            ToggleMode = true,
            StyleClasses = { "ButtonSquare" },
            HorizontalExpand = true,
            // Margin = new Thickness(4, 1),
            Children =
            {
                new BoxContainer()
                {
                    HorizontalExpand = true,
                    Orientation = LayoutOrientation.Horizontal,
                    // Margin = new Thickness(2, 1);
                    Children =
                    {
                        (AmmoBar = new AmmoBar()),
                        (CooldownBar = new AmmoBar()),
                    },
                },
            },
        });
    }
}
public sealed class AmmoBar : Control
{
    private int _value;
    public int Value
    {
        get
        {
            return _value;
        }
        set
        {
            _value = value;
            _bar.Value = value;
            _label.Text = value.ToString();
        }
    }

    public int MaxValue
    {
        get => field;
        set
        {
            field = value;
            _bar.MaxValue = value;
        }
    }

    public Label _label;
    public ProgressBar _bar;

    public AmmoBar()
    {
        MinHeight = 15;
        HorizontalExpand = true;
        VerticalAlignment = VAlignment.Center;
        AddChild(new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(2, 1),
            Children =
            {
                new Control { MinSize = new Vector2(5, 0) },
                new Control
                {
                    HorizontalExpand = true,
                    MaxHeight = 18,
                    Children =
                    {
                        (_bar = new ProgressBar
                        {
                            MinValue = 0,
                        }),
                        (_label = new Label
                        {
                            StyleClasses = { StyleNano.StyleClassItemStatus },
                            Align = Label.AlignMode.Center
                        })
                    }
                },
                new Control { MinSize = new Vector2(5, 0) },
            }
        });
    }
}
