// Copyright Rane (elijahrane@gmail.com) 2025
// All rights reserved. Relicensed under AGPL with permission

using System.Linq;
using System.Numerics;
using System.Text.RegularExpressions;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Mono.FireControl;
using Content.Shared._Mono.ShipGuns;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
namespace Content.Client._Mono.FireControl.UI;

[GenerateTypedNameReferences]
public sealed partial class FireControlWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly ILogManager _logger = default!;
    private ISawmill _sawmill = default!;
    public FireControlNavControl Radar => NavRadar;
    public Action? OnServerRefresh;
    public Action? OnWeaponSelectionChanged;
    /// <summary>
    /// Maps fire group names to the FireGroupContainer representing them
    /// </summary>
    public Dictionary<string, FireGroupContainer> GroupToContainer = [];
    /// <summary>
    /// Maps weapon NetEntities to the FireGroupContainer that contains them
    /// </summary>
    public Dictionary<NetEntity, AmmoBar> AmmoBarMap = [];
    private FireControlConsoleBoundInterfaceState? _currentState;

    public FireControlWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        RefreshButton.OnPressed += _ => OnServerRefresh?.Invoke();
        SelectAllButton.OnPressed += SelectAllFireGroups;
        UnselectAllButton.OnPressed += UnselectAllFireGroups;
        _sawmill = _logger.GetSawmill("firecont");
    }

    private void SelectAllFireGroups(BaseButton.ButtonEventArgs args)
    {
        // TODO: this approach still sucks
        foreach (var container in GroupToContainer.Values)
        {
            container.GroupButton.Pressed = true;
        }
        OnWeaponSelectionChanged?.Invoke();
        UpdateAllFireGroups();
    }

    private void UnselectAllFireGroups(BaseButton.ButtonEventArgs args)
    {
        foreach (var container in GroupToContainer.Values)
        {
            container.GroupButton.Pressed = false;
        }
        OnWeaponSelectionChanged?.Invoke();
        UpdateAllFireGroups();
    }

    public List<NetEntity>? GetSelectedWeapons()
    {
        if (_currentState == null)
        {
            return null;
        }

        List<NetEntity> weapons = [];
        foreach (var (group, container) in GroupToContainer)
        {
            if (container.GroupButton.Pressed)
            {
                weapons.AddRange(_currentState.FireGroups[group].Select(w => w.NetEntity));
            }
        }

        return weapons;
    }

    // private void SelectBallisticWeapons(BaseButton.ButtonEventArgs args)
    // {
    //     // First unselect all weapons
    //     foreach (var container in WeaponsList.Values)
    //     {
    //         container.WeaponButton.Pressed = false;
    //     }
    //
    //     // Then select only ballistic weapons
    //     foreach (var kvp in WeaponsList)
    //     {
    //         var weaponEntity = kvp.Key;
    //         var button = kvp.Value.WeaponButton;
    //
    //         if (_weaponTypes.TryGetValue(weaponEntity, out var type) && type == ShipGunType.Ballistic)
    //         {
    //             button.Pressed = true;
    //         }
    //     }
    //
    //     OnWeaponSelectionChanged?.Invoke();
    //     UpdateAllWeaponButtonTexts();
    // }


    /// <summary>
    /// Updates the text of a weapon button based on its selection state and manual reload status.
    /// </summary>
    // private void UpdateFireGroup(FireGroupContainer container, List<FireControllableEntry> controllables)
    // {
    //     var button = container.GroupButton;
    //     var ammoBar = container.WeaponAmmoBar;
    //     if (!controllable.AmmoCount.HasValue || !controllable.Capacity.HasValue)
    //     {
    //         ammoBar.MaxValue = 0;
    //         ammoBar.Value = 0;
    //     }
    //     else
    //     {
    //         ammoBar.Value = controllable.AmmoCount.Value;
    //         ammoBar.MaxValue = controllable.Capacity.Value;
    //     }
    //
    //     if (button.Pressed && controllable.HasManualReload && controllable.AmmoCount.HasValue)
    //     {
    //         button.Text = Loc.GetString("gunnery-gun-select-ammo", ("name", controllable.Name), ("ammo", controllable.AmmoCount.Value));
    //
    //         if (controllable.AmmoCount.Value == 0)
    //         {
    //             button.ModulateSelfOverride = Color.Red;
    //         }
    //         else
    //         {
    //             button.ModulateSelfOverride = null;
    //         }
    //     }
    //     else
    //     {
    //         button.Text = Loc.GetString("gunnery-gun-select", ("name", controllable.Name));
    //         button.ModulateSelfOverride = null;
    //     }
    // }
    private void UpdateFireGroup(string group, FireGroupContainer container)
    {
        if (_currentState == null)
            return;
        container.AmmoBarContainer.DisposeAllChildren();
        foreach (var controllable in _currentState.FireGroups[group])
        {
            // TODO: this is obviously not going to update properly. get these values from the BUI somehow (timer?).
            container.AmmoBarContainer.AddChild(new AmmoBar()
                { Value = controllable.AmmoCount ?? 0, MaxValue = controllable.Capacity ?? 0 });
        }
    }
    /// <summary>
    /// Updates all weapon button texts based on current selection state.
    /// </summary>
    private void UpdateAllFireGroups()
    {
        // TODO: Find out when this comes up
        if (_currentState == null)
            return;
        List<string>? toRemove = null;
        foreach (var (group, container) in GroupToContainer)
        {
            // TODO: what?
            // var controllable = _currentState?.FireControllables?.FirstOrDefault(c => c.NetEntity == netEntity);
            if (!_currentState.FireGroups.ContainsKey(group))
            {
                if (toRemove == null)
                    toRemove = [];
                toRemove.Add(group);
            }
            else
            {
            UpdateFireGroup(group, container);
            }
        }

        if (toRemove != null)
        {
            foreach (var group in toRemove)
            {
                GroupToContainer.Remove(group);
            }
        }
    }

    public void UpdateStatus(FireControlConsoleBoundInterfaceState state)
    {
        _currentState = state;
        NavRadar.UpdateState(state.NavState);

        if (state.Connected)
        {
            ServerStatus.Text = Loc.GetString("gunnery-window-connected");
            ServerStatus.FontColorOverride = Color.Green;
        }
        else
        {
            RefreshButton.Disabled = false;
            ServerStatus.Text = Loc.GetString("gunnery-window-disconnected");
            ServerStatus.FontColorOverride = Color.Red;
        }

        UpdateWeaponsList(state);
        UpdateAllFireGroups();
    }

    private void UpdateWeaponsList(FireControlConsoleBoundInterfaceState state)
    {
        foreach (var staleGroup in GroupToContainer.Keys.Except(state.FireGroups.Keys))
        {
            FireGroupsBox.RemoveChild(GroupToContainer[staleGroup]);
            GroupToContainer.Remove(staleGroup);
        }
        foreach (var (group, controllables) in state.FireGroups)
        {
            // We already have a container for the fire group, update it
            if (GroupToContainer.ContainsKey(group))
            {
                UpdateFireGroup(group, GroupToContainer[group]);
                continue;
            }
            // This fire group is new, create a container for it

            // Group selector button
            var button = new Button
            {
                ToggleMode = true,
                Text = group,
                StyleClasses = { "ButtonSquare OpenRight" },
                HorizontalExpand = true,
                Margin = new Thickness(4, 1),
            };
            button.OnToggled += _ =>
            {
                OnWeaponSelectionChanged?.Invoke();
                UpdateAllFireGroups();
            };

            // Ammo bars
            var ammoBarContainer = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                StyleClasses = { "transparentItemList" },
            };

            // Container for the button and its ammo bars
            var groupContainer = new FireGroupContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                StyleClasses = { "transparentItemList" },
                GroupButton = button,
                AmmoBarContainer = ammoBarContainer,
                GroupName = group,
            };
            groupContainer.AddChild(button);
            groupContainer.AddChild(ammoBarContainer);

            foreach (var controllable in controllables)
            {
                ammoBarContainer.AddChild(new AmmoBar()
                    { Value = controllable.AmmoCount ?? 0, MaxValue = controllable.Capacity ?? 0 }); // TODO: unfuck ammo stats
            }
            GroupToContainer[group] = groupContainer;
            FireGroupsBox.AddChild(groupContainer);
            UpdateFireGroup(group, groupContainer);
        }

        SelectAllButton.Disabled = state.FireControllables.Length == 0;
        UnselectAllButton.Disabled = state.FireControllables.Length == 0;
    }
}

public sealed class FireGroupContainer : BoxContainer
{
    public required string GroupName { get; set; }
    public required Button GroupButton { get; set; }

    public required BoxContainer AmmoBarContainer { get; set; }
}
public sealed class AmmoBar : Control
{
    private int _value;
    public int Value
    {
        get
        {
            return _value;
        }
        set
        {
            _value = value;
            _bar.Value = value;
            _label.Text = value.ToString();
        }
    }

    public int MaxValue
    {
        get => field;
        set
        {
            field = value;
            _bar.MaxValue = value;
        }
    }

    private Label _label;
    private ProgressBar _bar;

    public AmmoBar()
    {
        MinHeight = 15;
        HorizontalExpand = true;
        VerticalAlignment = VAlignment.Center;
        AddChild(new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(2, 1),
            Children =
            {
                new Control { MinSize = new Vector2(5, 0) },
                new Control
                {
                    HorizontalExpand = true,
                    MaxHeight = 18,
                    Children =
                    {
                        (_bar = new ProgressBar
                        {
                            MinValue = 0,
                        }),
                        (_label = new Label
                        {
                            StyleClasses = { StyleNano.StyleClassItemStatus },
                            Align = Label.AlignMode.Center
                        })
                    }
                },
                new Control { MinSize = new Vector2(5, 0) },
            }
        });
    }
}
